baseurl         = "/"
theme           = "hugo-casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Reflections"
  subtitle    = "The musings of my learning, travel, and general nerding out"

  cover       = "img/blog-cover.jpg"
  description = "Things I enjoy: coding, traveling, theater-going, and more."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "sarahlshowers"
  githubName = "sarahlshowers"
  linkedinName = "sarahlshowers"

  orgName = "© Sarah Showers"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Sarah Showers"
  authorAvatar = "images/avatar.jpg"
  authorLocation = "San Francisco, CA"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Learning"
  url = "/categories/learning/"
  weight = 99

[[menu.main]]
  name = "Travel"
  url = "/categories/travel/"
  weight = 100

# [[menu.main]]
#   name = "Family"
#   url = "/categories/family/"
#   weight = 99
theme = "hugo-casper-two"
